/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "auth.h"

oauth_response *
request_auth_1_svc(char **argp, struct svc_req *rqstp)
{
	static oauth_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

oauth_response *
request_token_1_svc(s_req_token *argp, struct svc_req *rqstp)
{
	static oauth_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

oauth_response *
validate_action_1_svc(s_val_act *argp, struct svc_req *rqstp)
{
	static oauth_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
approve_token_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
